version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: php-nginx-webserver
      working_dir: /application
      volumes:
          - ./webapp/:/usr/share/nginx/html:ro
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-nginx-php-fpm
      working_dir: /application
      volumes:
        - ./webapp/:/var/www/html
        - ./php/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
